### ISSUE TITLE
More documentation please!

### ISSUE THREAD

**Issue by mgifford** [github/accessibilityjs#21]
I'd love to have a write up so that this is easier to implement. Particularly as a part of an automated testing framework.

Thanks!

**Comment by mislav** [comment]
@mgifford What seems hard to implement about it right now? Is there something unclear after reading the example in the README?

Some pointers on what are the current stumbling blocks would be welcome.

**Comment by mgifford** [comment]
I guess mostly it boils down to me being a PHP guy. The JS stuff isn't something I do much with. 

For someone who knows CMS's (be it Drupal or WordPress) what is the best way to incorporate this? I'm not sure where to begin.

**Comment by mislav** [comment]
@mgifford Ah I see. This is a library aimed at JS developers. I think documenting integrations with different CMS's and frameworks would be out of scope for this project at the moment.

The library doesn't actually do much by itself, except scanning the page (or a specific container element) for violations and then passing those violations to a callback block. At runtime, these violations should perhaps be logged somewhere (as we do on GitHub.com). In test mode, these violations should be printed along with the test results and ideally fail the test suite. All this setup depends on the project at hand and what kind of testing framework was used, and is left as an exercise for the reader. In order to set it up, some JS experience will be required.

**Comment by mgifford** [comment]
No worries..  I have some JS experience, but really not that much. I may come back to this or bring one of my team to explore it more.
